name = "evivibakery"
compatibility_date = "2025-01-01"

# CRITICAL: This is the only configuration field required for the Pages Direct Upload flow
# if you are NOT using Pages Functions or other bindings.
pages_build_output_dir = "./dist"

# Remove the [build] section entirely as your build command is run separately before deployment.
# [build]
# command = "npm run build"