name = "cake-store"
compatibility_date = "2025-01-01"

[site]
bucket = "dist"

[build]
command = "npm run build"

[env.production]
workers_dev = false
route = "https://yourdomain.com/*"
zone_id = "your_zone_id"
